### ISSUE TITLE
as.matrix() should return a matrix 

### ISSUE THREAD

**Issue by RobinHankin** [RobinHankin/gyrogroup#4]
```
> a <- r3vel(6)
> as.matrix(a)[,1,drop=TRUE]
               x
[1,]  0.26123650
[2,] -0.14743235
[3,] -0.58923127
[4,] -0.15463424
[5,]  0.34821033
[6,] -0.01846731
> 
```

I would expect this to return a vector, not a one-column matrix.  We need ```as.matrix(a)``` to return ```unclass(a)```.

**Comment by koanarec** [comment]
I would like this feature please.

**Comment by RobinHankin** [comment]
OK Koanarec, I'm working on it, should have some functionality soon.

**Comment by RobinHankin** [comment]
Right now `as.matrix()` does nothing:

```
> a <- r3vel(9)
> identical(a,as.matrix(a))
[1] TRUE
> 
```
