### ISSUE TITLE
JOSE-Review: Add a pkgdown site

### ISSUE THREAD

**Issue by HaoZeke** [RobinHankin/gyrogroup#47]
This is part of the review [for JOSE](https://github.com/openjournals/jose-reviews/issues/196).

It would be helpful to have a `pkgdown` site hosted on github pages for the vignettes and package documentation (in addition to the PDFs as part of CRAN).

**Comment by RobinHankin** [comment]
Leaving open pending work on the celerity article, which is currently incomplete.  Will either delete it or improve it.
