### ISSUE TITLE
JOSE-Review: CI testsuite

### ISSUE THREAD

**Issue by HaoZeke** [RobinHankin/gyrogroup#49]
This is part of the review [for JOSE](https://github.com/openjournals/jose-reviews/issues/196).

I noticed that R CMD build action is also not present (though for a pure R package it shouldn't be required really). Tests on CI would be nice.

Similar to #48, I'd suggest running the ROpenSci [pkgcheck action](https://github.com/HaoZeke/fastMatMR/blob/main/.github/workflows/pkgcheck.yaml) which includes running tests and produces coverage metrics.

**Comment by RobinHankin** [comment]
package now clean under `workflows/R-cmd-check.yaml`.
